language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl COVERALLS=true

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  # Coveralls support
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls
  - git clone https://github.com/ceramic/copy-directory ~/lisp/copy-directory
  - git clone https://github.com/roswell/trivial-msi ~/lisp/trivial-msi
  - git clone https://github.com/eudoxia0/path-parse ~/lisp/path-parse
  - git clone https://github.com/eudoxia0/which ~/lisp/which

script:
  - cl -l fiveam
       -e '(setf fiveam:*debug-on-error* t)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(ql:quickload :imp-test)'
       -e '(imp-test:run-tests)'

notifications:
  email:
    - eudoxiahp@gmail.com
